# Generated by Django 3.2.8 on 2021-10-22 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='field',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='forms.form'),
        ),
        migrations.AlterField(
            model_name='field',
            name='type_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.fieldtype'),
        ),
    ]
