# Generated by Django 3.2.8 on 2021-10-25 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20211024_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='dependancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='forms.field'),
        ),
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
