# Generated by Django 3.2.8 on 2021-10-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20211025_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
